# Generated by Django 5.1.7 on 2025-03-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewerprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="content_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="education_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
