# Generated by Django 5.1.6 on 2025-04-10 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterModelOptions(
            name='viewerprofile',
            options={'verbose_name': 'Viewer Profile', 'verbose_name_plural': 'Viewer Profiles'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='viewerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='viewerprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='viewerprofile',
            name='content_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='viewerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='viewer_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
