# Generated by Django 5.1.7 on 2025-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_webcamrecording"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewerprofile",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="points_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
