# Generated by Django 5.2.16 on 2026-07-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emotion_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emotionframe',
            new_name='api_emotion_video_i_93a3c8_idx',
            old_name='emotion_frame_video_t_sec_idx',
        ),
    ]
