# Generated by Django 5.2.16 on 2026-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_emotion_frame_video_t_sec_idx_api_emotion_video_i_93a3c8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcamrecording',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
