name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for SonarQube to see history

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Create Backend .env File
        env:
          BACKEND_ENV_CONTENT: ${{ secrets.BACKEND_ENV_FILE }}
        run: printf "%s\n" "$BACKEND_ENV_CONTENT" > backend/.env
        shell: bash # Use printf for safer handling of special characters

      - name: Run tests and generate coverage report
        run: |
          cd backend
          pytest --cov=api --cov=backend --cov-report=xml:coverage.xml
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
