name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for SonarQube to see history

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Create Backend .env File
        run: |
          # Using echo block redirection as per user example
          {
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
            echo "DEBUG=${{ secrets.DEBUG }}" # Or set directly, e.g., DEBUG=False
            echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" # Or set directly, e.g., ENVIRONMENT=CI
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}"
            echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}"
            
            # Azure
            echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
            echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}"
            echo "AZURE_VIDEO_CONTAINER_NAME=${{ secrets.AZURE_VIDEO_CONTAINER_NAME }}"
            echo "AZURE_THUMBNAIL_CONTAINER_NAME=${{ secrets.AZURE_THUMBNAIL_CONTAINER_NAME }}"
            echo "GH_ACTIONS=${{ secrets.GH_ACTIONS }}"
            
            # Firebase
            echo "FIREBASE_TYPE=${{ secrets.FIREBASE_TYPE }}"
            echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
            echo "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}"
            # Using echo without quotes around the secret can be problematic for multi-line keys.
            # Ensure the secret value itself is formatted correctly (e.g., contains literal \n)
            # and doesn't contain characters that break the echo command.
            echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}"
            echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}"
            echo "FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}"
            echo "FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }}"
            echo "FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }}"
            echo "FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}"
            echo "FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}"
            echo "FIREBASE_UNIVERSE_DOMAIN=${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}"
            
          } > backend/.env
        shell: bash

      - name: Run tests and generate coverage report
        run: |
          cd backend
          pytest --cov=api --cov=backend --cov-report=xml:coverage.xml
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
